//! Installs (or upgrades) the canonical subsystem in a repository: the subsystem files are
//! copied byte-for-byte from the verifier's own `.ynventa`, and declarations are generated by
//! the legacy importer unless they already exist. Nothing outside `.ynventa/` is touched.

use super::atlas;
use crate::compact::facts::Knowledge;
use crate::declare;
use crate::protocol::{own_subsystem_dir, subsystem_files, SNAPSHOT_FILE};
use crate::repository::files::Files;
use std::path::Path;

#[derive(Debug, Default)]
pub struct Report {
    pub copied: usize,
    pub removed: usize,
    pub declarations_written: bool,
    pub dialects: Vec<String>,
    pub donors: usize,
    pub nodes: usize,
    pub waves: usize,
    pub facts: usize,
    /// Declaration files rewritten into the current grammar (`migrate schema`).
    pub migrated: Vec<String>,
}

pub fn scaffold(
    target: &Path,
    shard: Option<&str>,
    origin: Option<&str>,
    force: bool,
) -> Result<Report, String> {
    let mut r = Report::default();
    let src = own_subsystem_dir();
    let dst = target.join(".ynventa");
    let same = src.canonicalize().ok() == dst.canonicalize().ok();
    if !same {
        for f in subsystem_files(src) {
            let to = dst.join(&f);
            if let Some(p) = to.parent() {
                std::fs::create_dir_all(p).map_err(|e| format!("create {}: {e}", p.display()))?;
            }
            std::fs::copy(src.join(&f), &to).map_err(|e| format!("copy {f}: {e}"))?;
            r.copied += 1;
        }
        // Files a previous canonical snapshot had and this one does not are removed, so an
        // upgrade leaves exactly the canonical subsystem (repository state is never touched).
        let canonical: std::collections::BTreeSet<String> =
            subsystem_files(src).into_iter().collect();
        for f in subsystem_files(&dst) {
            if !canonical.contains(&f) {
                std::fs::remove_file(dst.join(&f)).map_err(|e| format!("remove stale {f}: {e}"))?;
                r.removed += 1;
            }
        }
        let snap = src.join("protocol.snapshot");
        if snap.exists() {
            std::fs::copy(&snap, target.join(SNAPSHOT_FILE))
                .map_err(|e| format!("copy snapshot: {e}"))?;
        }
    }
    if force
        || !declare::declared_dir(target)
            .join(declare::REPOSITORY_FILE)
            .exists()
    {
        let files = Files::scan(target).map_err(|e| e.to_string())?;
        let imp = atlas::import(target, &files, shard, origin);
        declare::store(target, &imp.declaration).map_err(|e| format!("write declarations: {e}"))?;
        if !imp.facts.is_empty() {
            Knowledge::add(target, &imp.facts).map_err(|e| format!("write knowledge: {e}"))?;
        }
        r.declarations_written = true;
        r.dialects = imp.dialects;
        r.donors = imp.declaration.donors.len();
        r.nodes = imp.declaration.repository.nodes.len();
        r.waves = imp.declaration.migration.waves.len();
        r.facts = imp.facts.len();
    } else {
        // Existing declarations follow the subsystem's grammar.
        r.migrated = declare::migrate_schema(target)?;
    }
    Ok(r)
}
