import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
const base=process.env.ECDEV_TEST_URL||'http://127.0.0.1:8765';
const client=new Client({name:'ecdev-conformance-client',version:'1.0.0'});
await client.connect(new StreamableHTTPClientTransport(new URL(base+'/mcp')));
try {
 const tools=await client.listTools();assert.equal(tools.tools.length,38);
 const officialFixtures=JSON.parse(await readFile(new URL('../../adapter/marketplace/tests/fixtures/official-responses.json',import.meta.url),'utf8'));
 const officialCase=officialFixtures.cases.find(c=>c.operation==='offers');
 const official=await client.callTool({name:'ecdev.product.analyze',arguments:{market:'AMAZON_US',asin:officialCase.asin,evidence_layer:'OFFICIAL_SP_API',include:['OFFERS'],fixture_responses:{offers:officialCase.response}}});
 assert.equal(official.isError,false);assert.equal(official.structuredContent.mode,'FIXTURE');assert.equal(official.structuredContent.network_calls,0);assert.equal(official.structuredContent.result.official_live_validation,'UNAVAILABLE');assert.equal(official.structuredContent.result.profit_expected,null);assert.equal(official.structuredContent.observations[0].raw_hash,createHash('sha256').update(officialCase.response.raw_body).digest('hex'));
 const officialStored=await client.callTool({name:'ecdev.runs.inspect',arguments:{run_id:official.structuredContent.run_id}});assert.equal(officialStored.isError,false);assert.equal(officialStored.structuredContent.raw_capture_verification,'VERIFIED_LOCAL_SHA256_NO_NETWORK');
 const officialDenied=await client.callTool({name:'ecdev.product.analyze',arguments:{market:'AMAZON_JP',asin:officialCase.asin,evidence_layer:'OFFICIAL_SP_API'}});assert.equal(officialDenied.isError,false);assert.equal(officialDenied.structuredContent.mode,'PLAN_ONLY');assert.equal(officialDenied.structuredContent.network_calls,0);assert.deepEqual(officialDenied.structuredContent.fallback_providers,[]);
 for(const name of ['ecdev.product.discover','ecdev.product.inspect','ecdev.product.compare','ecdev.provider.status','ecdev.provider.doctor','ecdev.monitor.create','ecdev.monitor.status'])assert.ok(tools.tools.some(t=>t.name===name),name);
 const social=await client.callTool({name:'ecdev.trend.discover',arguments:{query:'matcha',fixture_now:10000,sources:[{platform:'HACKER_NEWS',fixture_raw:JSON.stringify({hits:[{objectID:'sdk-1',title:'matcha glass',created_at_i:9000}]})}]}});
 // HN IDs are strictly numeric; malformed input must fail rather than create an observation.
 assert.equal(social.isError,false);assert.equal(social.structuredContent.source_complete,false);assert.match(social.structuredContent.provider_failures[0].reason,/INVALID_HN_ID/);
 const trend=await client.callTool({name:'ecdev.trend.discover',arguments:{query:'matcha',fixture_now:10000,sources:[{platform:'HACKER_NEWS',fixture_raw:JSON.stringify({hits:[{objectID:'101',title:'matcha glass',created_at_i:9000,points:0},{objectID:'102',title:'matcha glass',created_at_i:9100}]})}]}});
 assert.equal(trend.isError,false);assert.equal(trend.structuredContent.capture_mode,'FIXTURE');assert.equal(trend.structuredContent.mention_count,2);assert.equal(trend.structuredContent.budget_usage.request_count,0);assert.equal(trend.structuredContent.simulation_contribution,0);
 const zoned=await client.callTool({name:'ecdev.trend.discover',arguments:{query:'matcha',fixture_now:10000,sources:[{platform:'JSON_FEED',url:'https://example.org/feed.json',fixture_raw:JSON.stringify({version:'https://jsonfeed.org/version/1.1',items:[{id:'zone-1',url:'https://example.org/zone-1',content_text:'matcha time',date_published:'1970-01-01T11:30:00+09:00'},{id:'zone-unknown',url:'https://example.org/zone-unknown',content_text:'matcha time',date_published:'1970-01-01T02:30:00'}]})}]}});
 assert.equal(zoned.isError,false);assert.equal(zoned.structuredContent.capture_mode,'FIXTURE');assert.equal(zoned.structuredContent.mention_count,1);assert.equal(zoned.structuredContent.timestamp_unknown_excluded,1);assert.equal(zoned.structuredContent.captured_posts[0].published_at,9000);assert.equal(zoned.structuredContent.captured_posts[0].captured_at,10000);assert.equal(zoned.structuredContent.budget_usage.request_count,0);
 const trendEvidence=await client.callTool({name:'ecdev.trend.explain',arguments:{snapshot_id:trend.structuredContent.snapshot_id}});assert.equal(trendEvidence.isError,false);assert.equal(trendEvidence.structuredContent.observed_source_evidence.length,2);assert.equal(trendEvidence.structuredContent.score.learned,false);
 const trendWatch=await client.callTool({name:'ecdev.trend.watch',arguments:{query:'SDK social disabled watch',research:{query:'SDK social disabled watch',sources:[{platform:'HACKER_NEWS'}]},triggers:['TOPIC_MENTION_GROWTH'],interval_seconds:60,enabled:false}});assert.equal(trendWatch.isError,false);assert.equal(trendWatch.structuredContent.enabled,false);
 for(const name of ['ecdev.trend.discover','ecdev.trend.inspect','ecdev.trend.compare','ecdev.trend.watch','ecdev.trend.explain'])assert.ok(tools.tools.some(t=>t.name===name),name);
 const status=await client.callTool({name:'ecdev.system.status',arguments:{}});
 assert.equal(status.isError,false);assert.equal(status.structuredContent.name,'ECDEV');
 const providers=await (await fetch(base+'/api/providers')).json();
 if(providers.some(p=>p.id==='keepa'&&p.auth_state==='MISSING')) {
  const missing=await client.callTool({name:'ecdev.product.analyze',arguments:{market:'AMAZON_JP',asin:'B08N5WRWNW'}});
  assert.equal(missing.structuredContent.status,'UNAVAILABLE');assert.equal(missing.structuredContent.network_calls,0);
 }
 const intent={market:'AMAZON_JP',currency:'JPY',capital:300000,min_price:3000,max_price:6000,max_weight_g:700,minimum_margin_bps:2500,max_inventory_per_sku:150000};
 const run=await client.callTool({name:'ecdev.opportunity.search',arguments:intent});
 const value=run.structuredContent;assert.equal(value.mode,'PLAN_ONLY');assert.equal(value.status,'UNAVAILABLE');assert.equal(value.plan.steps.length,11);assert.deepEqual(value.observations,[]);
 const resource=await client.readResource({uri:'ecdev://run/'+value.run_id});assert.equal(JSON.parse(resource.contents[0].text).run_id,value.run_id);
 const replay=await client.callTool({name:'ecdev.runs.replay',arguments:{run_id:value.run_id}});assert.equal(replay.structuredContent.mode,'REPLAY');assert.equal(replay.structuredContent.network_calls,0);
 const scenario={currency:'JPY',fulfillment:'FBA',selling_price:4000,product_cost:800,freight:200,fulfillment_fee:500,referral_bps:1500,ppc:400,units:100,fixed_launch_cost:10000};
 const economics=await client.callTool({name:'ecdev.economics.simulate',arguments:scenario});assert.equal(economics.structuredContent.mode,'SIMULATED');assert.equal(economics.structuredContent.result.expected_profit,140000);
 const invalid=await client.callTool({name:'ecdev.economics.simulate',arguments:{...scenario,referral_bps:10001}});assert.equal(invalid.isError,true);
 const fixture=await (await fetch(base+'/api/research/example')).json();
 const research=await client.callTool({name:'ecdev.research.run',arguments:fixture});assert.equal(research.isError,false);
 const formatted=await client.callTool({name:'ecdev.research.run',arguments:{market:'PUBLIC_WEB',query:'SDK formatted price interpretation',max_pages:1,sources:[{url:'https://example.org/formatted-price',fixture_html:'<script type="application/ld+json">{"@type":"Product","name":"Formatted price","offers":{"price":"$12.99","priceCurrency":"USD"}}</script>'}]}});
 assert.equal(formatted.isError,false);assert.equal(formatted.structuredContent.mode,'FIXTURE');assert.equal(formatted.structuredContent.network_calls,0);
 const formattedOffers=formatted.structuredContent.candidates[0].product.observed_offers;
 assert.equal(formattedOffers[0].raw_price,'$12.99');assert.equal(formattedOffers[0].price_minor,null);assert.equal(formattedOffers[0].price_text_interpretation.state,'DERIVED');assert.equal(formattedOffers[0].price_text_interpretation.result.amount,'12.99');assert.equal(formattedOffers[0].price_text_interpretation.result.currency,'$');assert.equal(formattedOffers[0].price_text_interpretation.used_for_observed_price,false);
 assert.equal(research.structuredContent.mode,'FIXTURE');assert.equal(research.structuredContent.cost_minor,0);assert.equal(research.structuredContent.funnel.discovered,3);assert.equal(research.structuredContent.funnel.rejected,2);assert.equal(research.structuredContent.completeness.evidence_mode,'FIXTURE');assert.equal(research.structuredContent.completeness.live_zero_paid_research_coverage_bps,null);
 const verifiedRun=await client.callTool({name:'ecdev.runs.inspect',arguments:{run_id:research.structuredContent.run_id}});assert.equal(verifiedRun.isError,false);assert.equal(verifiedRun.structuredContent.raw_capture_verification,'VERIFIED_LOCAL_SHA256_NO_NETWORK');
 const verifiedGraph=await client.callTool({name:'ecdev.evidence.graph',arguments:{}});assert.equal(verifiedGraph.isError,false);assert.equal(verifiedGraph.structuredContent.raw_capture_verification,'VERIFIED_LOCAL_SHA256_NO_NETWORK');
 const forbiddenFollowUp=await client.callTool({name:'ecdev.research.run',arguments:{market:fixture.market,query:'Fixture isolation',follow_up_run_id:research.structuredContent.run_id}});assert.equal(forbiddenFollowUp.isError,true);
 const discovery=await client.callTool({name:'ecdev.product.discover',arguments:fixture});assert.equal(discovery.isError,false);assert.equal(discovery.structuredContent.mode,'FIXTURE');
 const candidates=discovery.structuredContent.candidates;
 const inspect=await client.callTool({name:'ecdev.product.inspect',arguments:{candidate_id:candidates[0].id}});assert.equal(inspect.isError,false);assert.equal(inspect.structuredContent.id,candidates[0].id);
 const comparison=await client.callTool({name:'ecdev.product.compare',arguments:{candidate_ids:candidates.slice(0,2).map(c=>c.id)}});assert.equal(comparison.isError,false);assert.equal(comparison.structuredContent.network_calls,0);
 const providerStatus=await client.callTool({name:'ecdev.provider.status',arguments:{}});assert.equal(providerStatus.isError,false);assert.ok(Array.isArray(providerStatus.structuredContent.items));const officialProfile=providerStatus.structuredContent.items.find(p=>p.id==="amazon-sp-api");assert.equal(officialProfile.live_supported,true);assert.equal(officialProfile.live_authorized,false);
 const watchList=await client.callTool({name:'ecdev.monitor.status',arguments:{}});assert.ok(Array.isArray(watchList.structuredContent.items));
 const watchArgs={enabled:false,market:'PUBLIC_WEB',query:'SDK disabled watch',targets:['https://example.org/product'],interval_seconds:60};
 const watch=await client.callTool({name:'ecdev.monitor.create',arguments:watchArgs});assert.equal(watch.isError,false);assert.equal(watch.structuredContent.status,'DISABLED');
 const watchStatus=await client.callTool({name:'ecdev.monitor.status',arguments:{watch_id:watch.structuredContent.watch_id}});assert.equal(watchStatus.isError,false);assert.equal(watchStatus.structuredContent.status,'DISABLED');
 const budget=await client.callTool({name:'ecdev.provider.budget',arguments:{}});assert.equal(budget.structuredContent.policy.per_month_minor,0);
 const api=await fetch(base+'/api/runs/'+value.run_id);assert.equal((await api.json()).run_id,value.run_id);
 for(const path of ['/health','/api/donors','/api/providers','/metrics','/','/app.js','/style.css'])assert.equal((await fetch(base+path)).status,200,path);
 assert.equal((await fetch(base+'/api/status',{headers:{Origin:'https://example.org'}})).status,403);
 assert.equal((await fetch(base+'/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream','MCP-Protocol-Version':'invalid'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/list'})})).status,400);
 const abort=new AbortController();const sse=await fetch(base+'/events',{signal:abort.signal});const reader=sse.body.getReader();const chunk=await reader.read();assert.match(new TextDecoder().decode(chunk.value),/event: run/);abort.abort();
 console.log(JSON.stringify({status:'PASS',transport:'SDK_STREAMABLE_HTTP',client:'@modelcontextprotocol/sdk',tool_count:tools.tools.length,source_scope_version:zoned.structuredContent.source_scope_version,timezone_fixture_snapshot_id:zoned.structuredContent.snapshot_id,timezone_and_source_scope:'PASS_OFFSET_UTC_UNKNOWN_ZONE_AND_FEED_WITHOUT_HN_LEAKAGE',plan_run_id:value.run_id,replay_run_id:replay.structuredContent.run_id,economics_run_id:economics.structuredContent.run_id,fixture_research_run_id:research.structuredContent.run_id,zero_paid_research:'PASS_FIXTURE_MODE',live_e2e:status.structuredContent.live_e2e,live_validation_scope:'NO_LIVE_ACQUISITION_IN_THIS_SMOKE_TEST'},null,2));
} finally {await client.close();}
