&[
Technology { key: "commerce.economics", name: "commerce.economics", kind: TechnologyKind::Algorithm, claimed: TechnologyLifecycle::Experimental, purpose: "Deterministic arithmetic in currency minor units; all fees supplied assumptions", implements: &["commerce.unit-economics"], node: "commerce", sources: &["domain/commerce/src/economics.rs"], invariants: &[], proofs: &[Proof { kind: ProofKind::Regression, locator: "domain/commerce/src/economics.rs::known_unit_economics" },Proof { kind: ProofKind::Regression, locator: "domain/commerce/src/economics.rs::extreme_inputs_return_errors_without_panicking" }], lineage: &[], relations: &[], norl: NorlRelevance::Unresolved, claims: &[] },
Technology { key: "commerce.planning", name: "commerce.planning", kind: TechnologyKind::Algorithm, claimed: TechnologyLifecycle::Experimental, purpose: "Provider-independent capability DAG; no observations when providers unavailable", implements: &["commerce.intent-planning"], node: "commerce", sources: &["domain/commerce/src/planner.rs"], invariants: &[], proofs: &[], lineage: &[], relations: &[], norl: NorlRelevance::Unresolved, claims: &[] },
Technology { key: "commerce.storage", name: "commerce.storage", kind: TechnologyKind::Storage, claimed: TechnologyLifecycle::Experimental, purpose: "SQLite WAL transactions; persisted modes; replay performs zero network calls", implements: &["commerce.run-storage"], node: "commerce", sources: &["domain/commerce/src/service.rs"], invariants: &[], proofs: &[Proof { kind: ProofKind::Regression, locator: "domain/commerce/src/service.rs::durable_runs_replay_without_network" }], lineage: &[], relations: &[], norl: NorlRelevance::Unresolved, claims: &[] },
Technology { key: "commerce.server", name: "commerce.server", kind: TechnologyKind::Protocol, claimed: TechnologyLifecycle::Experimental, purpose: "One shared engine; official MCP SDK; local HTTP; durable event stream", implements: &["commerce.mcp","commerce.http","commerce.events"], node: "commerce.server", sources: &["apps/server/src/lib.rs"], invariants: &[], proofs: &[], lineage: &[], relations: &[], norl: NorlRelevance::Unresolved, claims: &[] },
Technology { key: "commerce.observability", name: "commerce.observability", kind: TechnologyKind::Runtime, claimed: TechnologyLifecycle::Experimental, purpose: "HTTP/events projections without duplicate formulas", implements: &["commerce.observability"], node: "commerce.web", sources: &["apps/web/src/app.ts"], invariants: &[], proofs: &[], lineage: &[], relations: &[], norl: NorlRelevance::Unresolved, claims: &[] },
Technology { key: "commerce.donor-census", name: "commerce.donor-census", kind: TechnologyKind::Parser, claimed: TechnologyLifecycle::Experimental, purpose: "Full clone; locked Git blobs; every tracked file classified; unknown parsing stays partial", implements: &["commerce.donor-census"], node: "tools.commerce", sources: &["tools/commerce/census.py"], invariants: &[], proofs: &[], lineage: &[], relations: &[], norl: NorlRelevance::Unresolved, claims: &[] },
Technology { key: "commerce.keepa-current", name: "commerce.keepa-current", kind: TechnologyKind::Algorithm, claimed: TechnologyLifecycle::Experimental, purpose: "Only reviewed finite integer JSON contract; not a live provider or complete donor absorption", implements: &["commerce.keepa-current-value"], node: "commerce.keepa", sources: &["adapter/keepa/src/lib.rs"], invariants: &[], proofs: &[Proof { kind: ProofKind::Parity, locator: "adapter/keepa/src/lib.rs::donor_oracle_integer_json_contract" }], lineage: &[], relations: &[], norl: NorlRelevance::Unresolved, claims: &[] },
Technology { key: "commerce.keepa-product", name: "Native Keepa product boundary", kind: TechnologyKind::Protocol, claimed: TechnologyLifecycle::Experimental, purpose: "One explicit paid product request; raw response hashing; unknown monetary cost and freshness; live auth unverified", implements: &["commerce.keepa-product"], node: "commerce.keepa", sources: &["adapter/keepa/src/client.rs"], invariants: &[], proofs: &[Proof { kind: ProofKind::Regression, locator: "adapter/keepa/src/client.rs::missing_key_performs_no_network" }, Proof { kind: ProofKind::Regression, locator: "adapter/keepa/src/client.rs::currency_does_not_follow_donor_usd_formatter" }], lineage: &[], relations: &[], norl: NorlRelevance::Unresolved, claims: &[] },
Technology { key: "commerce.public-research", name: "commerce.public-research", kind: TechnologyKind::Runtime, claimed: TechnologyLifecycle::Experimental, purpose: "Native subset with explicit unknowns; no full donor parity or extinction", implements: &["fetch.http","fetch.redirect","extract.structured_data","extract.product"], node: "commerce.web-research", sources: &["adapter/web/src/lib.rs"], invariants: &[], proofs: &[Proof { kind: ProofKind::Regression, locator: "adapter/web/src/lib.rs::extraction_keeps_unknowns_and_minor_units" }], lineage: &[], relations: &[], norl: NorlRelevance::Unresolved, claims: &[] },
Technology { key: "commerce.zero-paid-research", name: "commerce.zero-paid-research", kind: TechnologyKind::Runtime, claimed: TechnologyLifecycle::Experimental, purpose: "Native subset with explicit unknowns; no full donor parity or extinction", implements: &["research.market","crawl.deduplicate","cache.ttl","monitor.change_detection"], node: "commerce", sources: &["domain/commerce/src/research.rs"], invariants: &[], proofs: &[Proof { kind: ProofKind::Regression, locator: "apps/server/src/lib.rs::zero_paid_research_e2e" }], lineage: &[], relations: &[], norl: NorlRelevance::Unresolved, claims: &[] },
Technology { key: "commerce.marketplace-ontology", name: "commerce.marketplace-ontology", kind: TechnologyKind::Runtime, claimed: TechnologyLifecycle::Experimental, purpose: "Native subset with explicit unknowns; no full donor parity or extinction", implements: &["marketplace.catalog"], node: "commerce", sources: &["domain/commerce/src/marketplace.rs"], invariants: &[], proofs: &[Proof { kind: ProofKind::Regression, locator: "domain/commerce/src/marketplace.rs::amazon_mapping_selects_market_and_keeps_unknowns" }], lineage: &[], relations: &[], norl: NorlRelevance::Unresolved, claims: &[] },
]
