Repository { id: "ecdev", name: "ECDEV", origin: "llgtrn/ECDEV", nodes: &[
Node { key: "governance", kind: NodeKind::Governance, concept: Concept::Subsystem, name: "ECDEV governance", path: ".ecdev", canonical_path: ".ecdev", lifecycle: NodeLifecycle::Active, provides: &[], requires: &[], reuses: &[], inputs: &[], outputs: &[], lineage: &[] },
Node { key: "commerce", kind: NodeKind::Domain, concept: Concept::Subsystem, name: "commerce", path: "domain/commerce", canonical_path: "domain/commerce", lifecycle: NodeLifecycle::Active, provides: &["research.evidence-decisions", "research.information-gain", "research.evidence-completeness", "monitor.persisted-watch", "commerce.economics-uncertainty", "competition.observed", "demand.proxy", "commerce.entity-resolution", "crawl.frontier", "url.identity", "commerce.unit-economics", "commerce.intent-planning", "commerce.run-storage", "marketplace.catalog", "crawl.deduplicate", "cache.ttl", "monitor.change_detection", "research.market", "social.cluster", "social.link", "social.model", "social.rank-exposure", "social.score", "social.separation", "social.snapshot", "social.thresholds", "social.watch", ], requires: &[], reuses: &[], inputs: &[], outputs: &[], lineage: &[] },
Node { key: "commerce.server", kind: NodeKind::Application, concept: Concept::Service, name: "commerce.server", path: "apps/server", canonical_path: "apps/server", lifecycle: NodeLifecycle::Active, provides: &["commerce.mcp", "commerce.http", "commerce.events"], requires: &[], reuses: &[], inputs: &[], outputs: &[], lineage: &[] },
Node { key: "commerce.web", kind: NodeKind::Application, concept: Concept::Interface, name: "commerce.web", path: "apps/web", canonical_path: "apps/web", lifecycle: NodeLifecycle::Active, provides: &["commerce.observability"], requires: &[], reuses: &[], inputs: &[], outputs: &[], lineage: &[] },
Node { key: "tools.commerce", kind: NodeKind::Tool, concept: Concept::Subsystem, name: "tools.commerce", path: "tools/commerce", canonical_path: "tools/commerce", lifecycle: NodeLifecycle::Active, provides: &["commerce.donor-census"], requires: &[], reuses: &[], inputs: &[], outputs: &[], lineage: &[] },
Node { key: "research.commerce", kind: NodeKind::Research, concept: Concept::Dataset, name: "research.commerce", path: "research/commerce", canonical_path: "research/commerce", lifecycle: NodeLifecycle::Active, provides: &[], requires: &[], reuses: &[], inputs: &[], outputs: &[], lineage: &[] },
Node { key: "commerce.tests", kind: NodeKind::Test, concept: Concept::Evaluation, name: "commerce.tests", path: "tests/commerce", canonical_path: "tests/commerce", lifecycle: NodeLifecycle::Active, provides: &[], requires: &[], reuses: &[], inputs: &[], outputs: &[], lineage: &[] },
Node { key: "commerce.marketplace", kind: NodeKind::Adapter, concept: Concept::Subsystem, name: "Official marketplace protocol boundary", path: "adapter/marketplace", canonical_path: "adapter/marketplace", lifecycle: NodeLifecycle::Active, provides: &["marketplace.official-product"], requires: &[], reuses: &[], inputs: &["explicit market ASIN intent and supplied fixture captures"], outputs: &["region-bound catalog offers and estimated fees with raw provenance"], lineage: &["amzn--selling-partner-api-models"] },
Node { key: "commerce.keepa", kind: NodeKind::Adapter, concept: Concept::Subsystem, name: "Keepa boundary normalization", path: "adapter/keepa", canonical_path: "adapter/keepa", lifecycle: NodeLifecycle::Active, provides: &["commerce.keepa-current-value", "commerce.keepa-product"], requires: &[], reuses: &[], inputs: &["finite integer JSON"], outputs: &["optional current value"], lineage: &["purahmanian--keepa-mcp"] },
Node { key: "commerce.web-research", kind: NodeKind::Adapter, concept: Concept::Subsystem, name: "Native public web research", path: "adapter/web", canonical_path: "adapter/web", lifecycle: NodeLifecycle::Active, provides: &["marketplace.public-amazon", "extract.publication-time", "extract.price-number", "extract.price-public-api", "extract.page-product", "extract.declared-document", "extract.microdata-graph", "supplier.public-leads", "extract.page-role", "crawl.robots", "fetch.redirect", "extract.structured_data", "fetch.http", "extract.product", "social.query", ], requires: &[], reuses: &[], inputs: &[], outputs: &[], lineage: &[] },

], edges: &[Edge { from: "commerce.server", to: "commerce.marketplace", kind: EdgeKind::DependsOn, scope: Scope::Runtime }, Edge { from: "commerce.marketplace", to: "commerce", kind: EdgeKind::DependsOn, scope: Scope::Runtime }, Edge { from: "commerce.server", to: "commerce.web-research", kind: EdgeKind::DependsOn, scope: Scope::Runtime }, Edge { from: "commerce.web-research", to: "commerce", kind: EdgeKind::DependsOn, scope: Scope::Runtime },Edge { from: "commerce.server", to: "commerce.keepa", kind: EdgeKind::DependsOn, scope: Scope::Runtime }, Edge { from: "commerce.keepa", to: "commerce", kind: EdgeKind::DependsOn, scope: Scope::Runtime }, Edge { from: "commerce.server", to: "commerce", kind: EdgeKind::DependsOn, scope: Scope::Runtime }, Edge { from: "commerce.web", to: "commerce", kind: EdgeKind::Calls, scope: Scope::Runtime }] }
