"""Measure the actual native wave and embed a self-contained MCP research schema."""
import collections,json,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[2]
def read(path):return json.loads((ROOT/path).read_text(encoding='utf-8'))
def main():
 schema=read('tools/commerce/schemas/research.schema.json');schema['properties']['economics']=read('tools/commerce/schemas/scenario.schema.json');schema['properties']['allow_stale']={'type':'boolean','default':False};(ROOT/'tools/commerce/schemas/research.schema.json').write_text(json.dumps(schema,indent=2)+'\n',encoding='utf-8')
 metrics=read('research/commerce/metrics.json');reg=read('research/commerce/donors/registry.json');intake=read('research/commerce/expansion-intake.json');graph=read('research/commerce/expansion-capability-graph.json');symbols=0;unknown_files=0
 for d in reg['donors']:
  s=read('research/commerce/donors/census/'+d['donor_id']+'/summary.json');symbols+=s['symbols'];unknown_files+=s['unknown_files']
 metrics.update(symbols_censused=symbols,unknown_files=unknown_files,source_reviewed_contracts=len(graph['capabilities']),mapped_capabilities=len(graph['capabilities']),zero_cost_stage_count=9,research_stage_count=14,zero_cost_coverage_bps=9*10000//14)
 (ROOT/'research/commerce/metrics.json').write_text(json.dumps(metrics,indent=2)+'\n',encoding='utf-8')
 report={'phase':'DONOR_EXPANSION_AND_ZERO_PAID_NATIVE_RESEARCH','donors_before':10,'donors_after':len(reg['donors']),'new_donors':[d['candidate_identifier'].removeprefix('github:') for d in reg['donors'] if d['candidate_identifier'].removeprefix('github:') in intake['requested']],'repos_newly_full_cloned':15,'census':metrics,'mcp_tools_before':16,'mcp_tools_after':25,'native_tests_before':10,'native_tests_after':17,'zero_paid_proof':'PASS_FIXTURE_MODE; three source fixture candidates, two explicit price rejections, one screened; supplier/demand/risk unknown','optional_paid_proof':'SKIPPED_EXTERNAL_QUOTA','canonical_origin':'https://github.com/llgtrn/.Ynventa-','canonical_commit':'c00a123c542b3c16fea4f82b45a5e544a1870178','canonical_subsystem':'BYTE_IDENTICAL','donor_extinction':'NOT_YET','source_reviews':'research/commerce/expansion-capability-graph.json','runtime_seed_donor_dependencies':0,'marketplace':'Official Amazon Catalog Items schema mapping begun; live SP-API adapter absent','browser':'Native task/observation abstraction; no browser runtime configured','remaining':['ECDEV absent from canonical upstream shard list; full canonical dogfood conformance test remains failing','Full semantic review and remaining source/classification unknowns; structural census is not complete absorption','Live official marketplace/demand/supplier/PPC/regulatory evidence','Browser sessions and runtime adapter; robots wildcard semantics remain conservatively denied','Automatic watch scheduling/notifications and advanced crawling priorities/backpressure','Learned ranking and donor-behavior oracle parity beyond the reviewed current-value primitive','Foundational libraries remain external; no full V1 extinction'],'next_absorption_target':'Crawlee normalized URL frontier: persistent pending/leased/handled states with cancellation, retries and oracle fixtures'}
 (ROOT/'research/commerce/wave-report.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8');print(json.dumps(metrics,indent=2))
if __name__=='__main__':main()
